server:
  port: 8081

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**

        - id: feedback
          uri: lb://feedback
          predicates:
            - Path=/feedback/**
      globalcors:
        corsConfigurations:
          '[/]':
            allowedOrigins: "http://localhost:63342"
            allowedMethods: "*"
            allowedHeaders: "*"



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,gateway
