eureka:
  client:
    register-with-eureka: true       # Optional (only needed if gateway should be discoverable)
    fetch-registry: true             # Required to discover other services
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5  # Refresh service list every 5s (dev only)
  instance:
    prefer-ip-address: true

server:
  port: 8070
spring:
  application:
    name: User
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
